replicaCount: 2

image:
  repository: santhi198/first-class-project
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer   
  port: 3000

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false
  hosts: []
  tls: false

nameOverride: ""
fullnameOverride: ""
